In [1]:
import numpy as np

## Hypothesis Function For a Single Instance

Implement the `compute_hypothesis_for_single_instance()` function, which computes the hypothesis value (linear regression) for an instance using vectorization.

**Arguments:**

* **`x`** : Feature values of an instance.
  * A 2D numpy array of shape (num of features, 1)

* **`theta`** : Parameters ($\theta_0, \theta_1,..,\theta_n$)
  * A 2D numpy array of shape (num of features + 1, 1)

**Returns:**

* Hypothesis value for the given instance
<br>$\hspace{20mm}h_{\theta}(x)= \theta^Tx$

In [89]:
def compute_hypothesis_for_single_instance(x, theta):
  #ADD YOUR CODE HERE
  x = np.insert(x,0,np.array([1]),axis = 0)
  h = np.dot(np.transpose(theta), x)
  if h.shape == (1,1):
    return h[0,0]
  return h

In [90]:
# SAMPLE TEST CASE
x = np.array([[5], [2.1], [7], [6.3]])
theta = np.array([[0.1], [0.3], [-0.5], [-0.2], [0.4]])
h = compute_hypothesis_for_single_instance(x, theta)
print(np.round(h,3))


1.67


**Expected Output:**
```
1.67
```

## Hypothesis Function For Multiple Instances

Implement the `compute_hypothesis_for_multiple_instances()` function, which computes the hypothesis value (linear regression) for multiple instances using vectorization.

**Arguments:**

* **`X`** : Design Matrix (Feature values of multiple instances).
  * A 2D numpy array of shape (num of instances, number of features)

* **`theta`** : Parameters ($\theta_0, \theta_1,..,\theta_n$)
  * A 2D numpy array of shape (num of features + 1, 1)

**Returns:**

* Hypothesis value for each instance.
  * A 2D numpy array of shape (num of instances, 1)
<br><br>$\hspace{20mm}h_{\theta}(X)= X\theta$

In [77]:
def compute_hypothesis_for_multiple_instances(X, theta):
  #ADD YOUR CODE HERE
  X= np.insert(X, 0, 1,axis=1)
  h= np.dot(X,theta)
  return h


In [78]:
# SAMPLE TEST CASE
X = np.array([[5, 2.4, 3.11], 
              [2.1, 4.6, 2.33], 
              [7, 9.21, 6.28], 
              [6.3, 6.12, 0.23]])

theta = np.array([[0.1], [0.3], [1.2], [3.21]])
H = compute_hypothesis_for_multiple_instances(X, theta)
print(np.round(H,3))



[[14.463]
 [13.729]
 [33.411]
 [10.072]]


**Expected Output:**
```
[[14.463]
 [13.729]
 [33.411]
 [10.072]]
```

## Cost Function in Linear Regression
Implement the `compute_cost()` function, which computes the cost (MSE in linear regression) using vectorization.

**Arguments:**

* **`X`** : Design Matrix.
  * A 2D numpy array of shape (num of instances, num of features)

* **`Y`** : True values corresponding to each training instance in $X$.
  * A 2D numpy array of shape (num of instances, 1)

* **`theta`** : Parameters ($\theta_0, \theta_1,..,\theta_n$)
  * A 2D numpy array of shape (num of features + 1, 1)

**Returns:**

* Cost value with the given parameters and data
<br><br>$\hspace{20mm}J(\theta) = \frac{1}{2m}(X\theta - Y)^T(X\theta-Y)$


In [91]:
def compute_cost(X, Y, theta):
  #ADD YOUR CODE HERE
  L = compute_hypothesis_for_multiple_instances(X,theta) - Y
  s = X.shape
  m = s[0]
  J = np.dot(np.transpose(L), L)/(2*m)
  if J.shape == (1,1):
    return J[0,0]

  return J 


In [92]:
# SAMPLE TEST CASE
X = np.array([[5.1, 2, 7, 6],
             [6, 1, 0, 4]])
Y = np.array([[2.1], [3]])
theta = np.array([[0.1], [0.3], [-0.5], [-0.2], [0.4]])
print(np.round(compute_cost(X, Y, theta),3))
# print(compute_hypothesis_for_multiple_instances(X, theta))
# np.dot(np.transpose(compute_hypothesis_for_multiple_instances(X, theta) - Y), compute_hypothesis_for_multiple_instances(X, theta) - Y)/4
# X.shape

0.055


**Expected Output:**
```
0.055
```

## Gradient of Cost Function in Linear Regression

Implement the `compute_gradient_of_cost_function()` function which computes the gradient of the cost function using vectorization.

**Arguments:**

* **`X`** : Design Matrix.
  * A 2D numpy array of shape (num of instances, num of features)

* **`Y`** : True values corresponding to each training instance in $X$.
  * A 2D numpy array of shape (num of instances, 1)

* **`theta`** : Parameters ($\theta_0, \theta_1,..,\theta_n$)
  * A 2D numpy array of shape (num of features + 1, 1)

**Returns:**

* Gradient of the cost function corresponding to each feature.
  * A 2D numpy array of shape (num of features + 1, 1).
<br><br>$\hspace{20mm}{d J \over d \theta} = \frac{1}{m}X^T(X\theta - Y)$


In [93]:
def compute_gradient_of_cost_function(X, Y, theta):
  #ADD YOUR CODE HERE
  L = compute_hypothesis_for_multiple_instances(X, theta) - Y
  s = X.shape
  m = s[0]
  X = np.insert(X,0,1,axis=1)
  return np.dot(np.transpose(X), L)/m

In [94]:
# SAMPLE TEST CASE
X = np.array([[5, 2, 7, 6],
             [6, 1, 0, 4]])
Y = np.array([[2], [3]])
theta = np.array([[0.1], [0.3], [-0.5], [-0.2], [0.4]])
gradients = compute_gradient_of_cost_function(X, Y, theta)
print(np.round(gradients,3))
# np.dot(np.transpose(X), compute_hypothesis_for_multiple_instances(X, theta) -Y)/m


[[-0.2]
 [-1. ]
 [-0.4]
 [-1.4]
 [-1.2]]


**Expected Output:**
```
[[-0.2]
 [-1. ]
 [-0.4]
 [-1.4]
 [-1.2]]

```